<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWN5QxUd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWN5QxUd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWN5QxUd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWN5QxUd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWN5QxUd\App_KernelDevDebugContainer([
    'container.build_hash' => 'WN5QxUd',
    'container.build_id' => 'b92f4418',
    'container.build_time' => 1587626499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWN5QxUd');
