<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGAlqX2Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGAlqX2Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGAlqX2Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGAlqX2Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGAlqX2Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'GAlqX2Z',
    'container.build_id' => 'c8f93341',
    'container.build_time' => 1587627266,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGAlqX2Z');
